<a href="https://colab.research.google.com/github/JonathanBheri/Machine-Learning/blob/master/Credit_card_testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import sklearn as ml
from sklearn import tree
from sklearn import preprocessing
#data= pd.read_csv('creditcard.csv')

In [0]:
from sklearn import datasets as ds
help(ds.mldata)

In [0]:
url='https://raw.githubusercontent.com/nsethi31/Kaggle-Data-Credit-Card-Fraud-Detection/master/creditcard.csv'
data= pd.read_csv(url)

In [0]:
x=data.iloc[:,:-1]
y=data.iloc[:,-1]

In [0]:
help(y)

In [0]:
unique, counts = np.unique(y, return_counts=True)
dict(zip(unique, counts))

{0: 284315, 1: 492}

In [0]:
(np.shape(x)[1])

30

In [0]:
x=preprocessing.scale(x)

In [0]:
transformer = preprocessing.RobustScaler().fit(x)
transformer
x=transformer.transform(x)

RobustScaler(copy=True, quantile_range=(25.0, 75.0), with_centering=True,
       with_scaling=True)

Robust Scaling of data which will help with outliers

In [0]:
min_max_scaler = preprocessing.MinMaxScaler()
x = min_max_scaler.fit_transform(x)

Split the data into training and test

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=22)

In [0]:
help(ml)

# Decision tree

In [0]:

X_undersample,y_undersample=newdata()
X_train, X_test, y_train, y_test = train_test_split(X_undersample,y_undersample, test_size=0.8, random_state=2)

In [0]:
model=tree.DecisionTreeClassifier()

model=model.fit(X_train,y_train)

In [0]:
dt_y_pred=model.predict(X_test)

In [0]:
help(ml.metrics.classification)

In [0]:
ml.metrics.classification.confusion_matrix(y_test, dt_y_pred)

array([[346,  38],
       [ 42, 362]])

In [0]:
from sklearn.ensemble import AdaBoostClassifier

In [0]:
adab=AdaBoostClassifier(tree.DecisionTreeClassifier(max_depth=3),
                         algorithm="SAMME",
                         n_estimators=50)
adab.fit(X_train,y_train)


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(algorithm='SAMME',
          base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
          learning_rate=1.0, n_estimators=50, random_state=None)

In [0]:
dt_y_pred=adab.predict(X_test)
ml.metrics.classification.confusion_matrix(y_test, dt_y_pred)

array([[371,  13],
       [ 44, 360]])

# Random Forest

In [0]:
from sklearn.ensemble import RandomForestClassifier



rf_model = RandomForestClassifier(n_estimators=500, max_depth=6,random_state=0)

In [0]:
rf_model.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=6, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [0]:
rf_y_pred=rf_model.predict(X_test)
ml.metrics.classification.confusion_matrix(y_test, rf_y_pred)

array([[380,   4],
       [ 48, 356]])

# Neural networks

In [0]:
import tensorflow as tf
import keras

Using TensorFlow backend.


In [0]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Convolution1D, Flatten, Dropout
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence

Using TensorFlow backend.


In [0]:
url='https://raw.githubusercontent.com/nsethi31/Kaggle-Data-Credit-Card-Fraud-Detection/master/creditcard.csv'
Data= pd.read_csv(url)

In [0]:
X=Data.iloc[:,:-1]
y=Data.iloc[:,-1]

In [0]:
def newdata():
  url='https://raw.githubusercontent.com/nsethi31/Kaggle-Data-Credit-Card-Fraud-Detection/master/creditcard.csv'
  data= pd.read_csv(url)
  number_records_fraud = len(data[data.Class == 1])
  fraud_indices = np.array(data[data.Class == 1].index)

# Picking the indices of the normal classes
  normal_indices = data[data.Class == 0].index
 
# Out of the indices we picked, randomly select "x" number (number_records_fraud)
  random_normal_indices = np.random.choice(normal_indices, number_records_fraud, replace = False)
  random_normal_indices = np.array(random_normal_indices)

# Appending the 2 indices
  under_sample_indices = np.concatenate([fraud_indices,random_normal_indices])

# Under sample dataset
  under_sample_data = data.iloc[under_sample_indices,:]

  X_undersample = under_sample_data.iloc[:, under_sample_data.columns != 'Class']
  transformer = preprocessing.RobustScaler().fit(X_undersample )
  transformer
  X_undersample =transformer.transform(X_undersample )
  y_undersample = under_sample_data.iloc[:, under_sample_data.columns == 'Class']
  return (X_undersample,y_undersample)
  


In [0]:
X_train, X_test, y_train, y_test = train_test_split(X_undersample,y_undersample, test_size=0.2, random_state=22)

In [0]:
nnmodel = Sequential()

In [0]:
nnmodel.add(Dense(32,activation='sigmoid',input_shape=(np.shape(X_train)[1],)  ))
nnmodel.add(Dense(16,activation='sigmoid'))
nnmodel.add(Dense(16,activation='linear'))
nnmodel.add(Dense(1,activation='softmax'))


In [0]:
nnmodel.compile(loss='mean_absolute_error', optimizer='Adamax', metrics=['categorical_accuracy'])
nnmodel.fit(X_train, y_train, epochs=2, batch_size=32)


Epoch 1/2
787/787 [==============================] - 2s 2ms/step - loss: 0.4930 - categorical_accuracy: 1.0000
Epoch 2/2
787/787 [==============================] - 0s 56us/step - loss: 0.4930 - categorical_accuracy: 1.0000


In [0]:
nn_y_pred= np.round(nnmodel.predict(X_test))

In [0]:
ml.metrics.classification.confusion_matrix(y_test, nn_y_pred)

array([[  0, 104],
       [  0,  93]])

In [0]:
nn_y_pred

In [0]:
scores = nnmodel.evaluate(x_test, y_test, verbose=0)
print("Mistakes: " , (scores[0]*np.shape(x_test)[0]))

NameError: ignored